# version: "3.9"

services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
  # auth-celery:
  #   build: ./auth-service
  #   command: celery -A your_project_name worker --loglevel=info
  #   depends_on:
  #     - redis
  #     - rabbitmq
  #   environment:
  #     - CELERY_BROKER_URL=${CELERY_BROKER_URL}
  #     - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}

  auth-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "01713447728"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5433:5432"

  company-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: companydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "01713447728"
    volumes:
      - company_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5434:5432"

  inventory-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "01713447728"
    volumes:
      - inventory_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5435:5432"

  auth-web:
    build:
      context: ./auth-service
    container_name: auth-service
    restart: unless-stopped
    command: >
      bash -c "until pg_isready -h auth-db -U postgres; do echo 'Waiting for auth-db...'; sleep 1; done;
               python manage.py migrate --noinput &&
               python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    env_file:
      - ./auth-service/.env
    depends_on:
      - auth-db
      - redis
    volumes:
      - ./auth-service:/usr/src/app

  company-web:
    build:
      context: ./company-service
    container_name: company-service
    restart: unless-stopped
    command: >
      bash -c "until pg_isready -h company-db -U postgres; do echo 'Waiting for company-db...'; sleep 1; done;
               python manage.py migrate --noinput &&
               python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8002:8000"
    env_file:
      - ./company-service/.env
    depends_on:
      - company-db
      - redis
      - auth-web
    volumes:
      - ./company-service:/usr/src/app

  inventory-web:
    build: ./inventory_service
    container_name: inventory-web
    restart: unless-stopped
    command: >
      bash -c "until pg_isready -h inventory-db -U postgres; do echo 'Waiting for inventory-db...'; sleep 1; done;
               python manage.py migrate --noinput &&
               python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8003:8000"
    env_file: ./inventory_service/.env
    depends_on:
      - inventory-db
      - redis
      - auth-web
    volumes:
      - ./inventory_service:/usr/src/app

  audit-worker:
    build: ./auth-service
    command: celery -A auth_service.celery_app worker --loglevel=info --concurrency=1
    env_file:
      - ./auth-service/.env
    depends_on:
      - redis
      - auth-db

  audit-subscriber:
    build: ./auth-service
    container_name: audit-subscriber
    command: python tools/audit_subscriber.py
    env_file: ./auth-service/.env
    depends_on:
      - redis
      - auth-db

volumes:
  auth_db_data:
  company_db_data:
  inventory_db_data:
