# Generated by Django 4.2 on 2025-09-16 04:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, null=True)),
                ('channel_email', models.BooleanField(default=True)),
                ('channel_webhook', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('emails', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, null=True)),
                ('wing_id', models.UUIDField(blank=True, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=0)),
                ('last_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.product')),
            ],
            options={
                'unique_together': {('product', 'company_id', 'wing_id')},
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('created_by_username', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.stock')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(blank=True, null=True)),
                ('wing_id', models.UUIDField(blank=True, null=True)),
                ('change', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('requested_by_id', models.UUIDField(blank=True, null=True)),
                ('requested_by_username', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approver_id', models.UUIDField(blank=True, null=True)),
                ('approver_username', models.CharField(blank=True, max_length=150, null=True)),
                ('approver_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(default='LOW_STOCK', max_length=50)),
                ('threshold', models.IntegerField()),
                ('available', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('external_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.stock')),
            ],
        ),
    ]
