# Generated by Django 4.2 on 2025-09-22 10:54

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_accounting_codes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO currency code, e.g. USD, BDT', max_length=3, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=Decimal('1.0'), max_digits=20)),
                ('is_base', models.BooleanField(default=False, help_text='Mark this as the system base currency (only one)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_base', 'code'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='bin_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(blank=True, default='INV', max_length=20)),
                ('next_invoice_number', models.BigIntegerField(default=1)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('template', models.CharField(choices=[('standard', 'Standard'), ('compact', 'Compact'), ('detailed', 'Detailed')], default='standard', max_length=32)),
                ('footer_note', models.TextField(blank=True)),
                ('sequence_name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='companies.company')),
                ('default_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_user_id', models.UUIDField(blank=True, help_text='Link to auth-service user id (optional)', null=True)),
                ('employee_code', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('cashier', 'Cashier'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('owner', 'Owner'), ('other', 'Other')], default='cashier', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.company')),
            ],
            options={
                'ordering': ['-date_joined', 'employee_code'],
            },
        ),
        migrations.AddIndex(
            model_name='invoicesettings',
            index=models.Index(fields=['company'], name='companies_i_company_e8828a_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'external_user_id'], name='companies_e_company_a1a7a8_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='companies_e_email_75ab58_idx'),
        ),
    ]
