# Generated by Django 4.2 on 2025-09-23 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_currency_company_bin_number_invoicesettings_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('accent_color', models.CharField(blank=True, max_length=7, null=True)),
                ('background_color', models.CharField(blank=True, max_length=7, null=True)),
                ('text_color', models.CharField(blank=True, max_length=7, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='company_icons/')),
                ('nav', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('ui_schema', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Setting',
            },
        ),
    ]
